---
sudo: true
language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run before test
before_script:
  - sudo mkdir /webDriver
  - sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - tar -xf geckodriver-v0.19.1-linux64.tar.gz
  - sudo mv gecko* /webDriver
  - export PATH=$PATH/:/webDriver
  - python manage.py runserver > /dev/null 2>&1 &

# command to run tests
script:
  - pytest
