# Generated by Django 2.0 on 2017-12-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compute_resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ip_address', models.CharField(max_length=15)),
                ('root_password', models.CharField(max_length=20)),
            ],
        ),
    ]
