# Generated by Django 2.0 on 2018-01-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compute_resource_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ip_address', models.CharField(max_length=15)),
                ('root_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Container_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=20, verbose_name='Image Name')),
                ('tag_name', models.CharField(max_length=20, verbose_name='Tag')),
                ('container_name', models.CharField(max_length=20, verbose_name='Container Name')),
                ('command', models.CharField(max_length=15, verbose_name='Command')),
                ('entry_point', models.CharField(max_length=15, verbose_name='Entry Point')),
            ],
        ),
        migrations.CreateModel(
            name='Create_host_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=15)),
                ('vm_os', models.CharField(max_length=15)),
                ('select_vm_profile', models.CharField(max_length=10)),
                ('select_compute', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Local_image_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dockerfile', models.TextField(verbose_name='Write Dockerfile here')),
                ('image_name', models.CharField(max_length=20, verbose_name='Image Name')),
                ('tag_name', models.CharField(default='latest', max_length=20, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Operating_system_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=15)),
                ('os_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=10)),
                ('ram', models.IntegerField()),
                ('cpus', models.IntegerField()),
                ('disk_size', models.IntegerField()),
            ],
        ),
    ]
