# Generated by Django 2.0 on 2017-12-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
