# Generated by Django 2.0 on 2017-12-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=10)),
                ('ram', models.IntegerField()),
                ('cpus', models.IntegerField()),
                ('disk_size', models.IntegerField()),
            ],
        ),
    ]
