# Generated by Django 2.0 on 2017-12-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='compute_resource',
            new_name='compute_resource_model',
        ),
        migrations.RenameModel(
            old_name='profile',
            new_name='profile_model',
        ),
    ]
