# Generated by Django 2.0 on 2017-12-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20171220_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_model',
        ),
    ]
