# Generated by Django 2.0 on 2017-12-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_profile_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=10)),
                ('ram', models.IntegerField()),
                ('cpus', models.IntegerField()),
                ('disk_size', models.IntegerField()),
                ('select_compute', models.CharField(choices=[(('test',), ('test',)), (('q',), ('q',)), (('rt',), ('rt',))], max_length=10)),
            ],
        ),
    ]
