# Generated by Django 2.0 on 2017-12-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_model',
            name='select_compute',
        ),
    ]
