# Generated by Django 2.0 on 2017-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_profile_model_select_compute'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_model',
            name='select_compute',
            field=models.CharField(choices=[('test', 'test'), ('q', 'q'), ('rt', 'rt'), ('final', 'final'), ('check', 'check'), ('qwerty', 'qwerty'), ('asdfghjk', 'asdfghjk')], default=None, max_length=10),
        ),
    ]
