# Generated by Django 2.0 on 2017-12-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_profile_model_select_compute'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_host_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=15)),
                ('vm_os', models.CharField(max_length=15)),
                ('select_vm_profile', models.CharField(choices=[('bn', 'bn')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='select_compute',
            field=models.CharField(choices=[('test', 'test'), ('q', 'q'), ('rt', 'rt'), ('final', 'final'), ('check', 'check'), ('qwerty', 'qwerty'), ('asdfghjk', 'asdfghjk'), ('poi', 'poi')], default=None, max_length=10),
        ),
    ]
