# Generated by Django 2.0 on 2017-12-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20171225_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='operating_system_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=15)),
                ('os_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='create_host_model',
            name='select_vm_profile',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='select_compute',
            field=models.CharField(choices=[('compute1', 'compute1'), ('compute2', 'compute2'), ('compute3', 'compute3'), ('compute4', 'compute4')], default=None, max_length=10),
        ),
    ]
