# Generated by Django 2.0 on 2017-12-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20171226_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operating_system_model',
            name='os_location',
            field=models.CharField(choices=[('f25', 'Fedora 25'), ('f26', 'Fedora 26'), ('f27', 'Fedora 27')], default=None, max_length=100),
        ),
    ]
