# Generated by Django 2.0 on 2017-12-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20171226_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operating_system_model',
            name='os_location',
            field=models.CharField(max_length=100),
        ),
    ]
