# Generated by Django 2.0 on 2017-12-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20171226_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='newContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_compute_resource', models.CharField(choices=[('compute1', 'compute1'), ('compute2', 'compute2'), ('compute3', 'compute3'), ('compute4', 'compute4'), ('compute5', 'compute5')], default=None, max_length=15, verbose_name='Select Compute Resource')),
                ('image_name', models.TextField(verbose_name='Image Name')),
                ('tag_name', models.TextField(verbose_name='Tag')),
                ('container_name', models.TextField(verbose_name='Container Name')),
                ('command', models.CharField(max_length=15, verbose_name='Command')),
                ('entry_point', models.CharField(max_length=15, verbose_name='Entry Point')),
            ],
        ),
        migrations.AlterField(
            model_name='compute_resource_model',
            name='ip_address',
            field=models.CharField(max_length=15, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='create_host_model',
            name='vm_os',
            field=models.CharField(choices=[('Fedora 25', 'Fedora 25'), ('Fedora 26', 'Fedora 26'), ('Fedora 27', 'Fedora 27'), ('Fedora26', 'Fedora26'), ('Fedora 25', 'Fedora 25')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='operating_system_model',
            name='os_location',
            field=models.CharField(max_length=100, verbose_name='OS Location'),
        ),
        migrations.AlterField(
            model_name='operating_system_model',
            name='os_name',
            field=models.CharField(max_length=15, verbose_name='OS Name'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='cpus',
            field=models.IntegerField(verbose_name='CPUs'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='disk_size',
            field=models.IntegerField(verbose_name='Disk Size(GiB)'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='ram',
            field=models.IntegerField(verbose_name='RAM(GiB)'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='select_compute',
            field=models.CharField(choices=[('compute1', 'compute1'), ('compute2', 'compute2'), ('compute3', 'compute3'), ('compute4', 'compute4'), ('compute5', 'compute5')], default=None, max_length=10),
        ),
    ]
