# Generated by Django 2.0 on 2017-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20171231_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcontainer',
            name='container_name',
            field=models.CharField(max_length=20, verbose_name='Container Name'),
        ),
        migrations.AlterField(
            model_name='newcontainer',
            name='image_name',
            field=models.CharField(max_length=20, verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='newcontainer',
            name='tag_name',
            field=models.CharField(max_length=20, verbose_name='Tag'),
        ),
    ]
