# Generated by Django 2.0 on 2017-12-31 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20171231_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newContainer',
            new_name='Container_model',
        ),
    ]
