# Generated by Django 2.0 on 2018-01-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20180101_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compute_resource_model',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
