# Generated by Django 2.0 on 2018-01-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_local_image_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local_image_model',
        ),
    ]
