# Generated by Django 2.0 on 2018-01-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_delete_local_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='container_model',
            name='dockerfile',
            field=models.TextField(null=True, verbose_name='Write Dockerfile here'),
        ),
    ]
