# Generated by Django 2.0 on 2018-01-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_container_model_dockerfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local_image_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dockerfile', models.TextField(verbose_name='Write Dockerfile here')),
            ],
        ),
        migrations.RemoveField(
            model_name='container_model',
            name='dockerfile',
        ),
    ]
