# Generated by Django 2.0 on 2018-01-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20180102_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_image_model',
            name='image_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Image Name'),
        ),
        migrations.AddField(
            model_name='local_image_model',
            name='tag_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Tag'),
        ),
    ]
