# Generated by Django 2.0 on 2018-01-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20180102_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_image_model',
            name='image_name',
            field=models.CharField(max_length=20, verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='local_image_model',
            name='tag_name',
            field=models.CharField(max_length=20, verbose_name='Tag'),
        ),
    ]
