# Generated by Django 2.0 on 2018-01-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20180102_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_model',
            name='select_compute',
        ),
        migrations.AlterField(
            model_name='container_model',
            name='select_compute_resource',
            field=models.CharField(choices=[('compute1', 'compute1'), ('compute2', 'compute2'), ('compute3', 'compute3'), ('compute4', 'compute4'), ('compute5', 'compute5'), ('testpc', 'testpc'), ('we', 'we'), ('qwerr', 'qwerr'), ('poiuy', 'poiuy'), ('hjt', 'hjt'), ('vgt', 'vgt')], default=None, max_length=15, verbose_name='Select Compute Resource'),
        ),
        migrations.AlterField(
            model_name='create_host_model',
            name='select_vm_profile',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('TestPC', 'TestPC')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='create_host_model',
            name='vm_os',
            field=models.CharField(choices=[('Fedora 25', 'Fedora 25'), ('Fedora 26', 'Fedora 26'), ('Fedora 27', 'Fedora 27'), ('Fedora26', 'Fedora26'), ('Fedora 25', 'Fedora 25'), ('testOS', 'testOS')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='local_image_model',
            name='tag_name',
            field=models.CharField(default='latest', max_length=20, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='ram',
            field=models.IntegerField(verbose_name='RAM(MiB)'),
        ),
    ]
