# Generated by Django 2.0 on 2018-01-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_create_host_model_select_compute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compute_resource_model',
            name='ip_address',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='container_model',
            name='select_compute_resource',
            field=models.CharField(choices=[('testpc', 'testpc'), ('poiuy', 'poiuy'), ('qwerty', 'qwerty'), ('jnlkn', 'jnlkn'), ('hfvljh', 'hfvljh')], default=None, max_length=15, verbose_name='Select Compute Resource'),
        ),
        migrations.AlterField(
            model_name='create_host_model',
            name='select_compute',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='create_host_model',
            name='select_vm_profile',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='create_host_model',
            name='vm_os',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='operating_system_model',
            name='os_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operating_system_model',
            name='os_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='cpus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='disk_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
